version: '3'
services:
  frontend:
    build:  frontend
    ports:
      - 80:80
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017

  polybot:
    build: polybot
    depends_on:
      - mongo
  yolo5:
    build: yolo5
    depends_on:
      - mongo
